apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  labels:
    {{- include "movies.labels" . | nindent 4 }}
spec:
  rules:
    - host: movies-{{ .Release.Namespace }}.demo.okteto.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
  tls:
  - hosts:
    - movies-{{ .Release.Namespace }}.demo.okteto.dev